ALTER TABLE savedlocations
    MODIFY locationtype ENUM ('FREE_MARKET','WORLDTOUR','FLORINA','INTRO','SUNDAY_MARKET','MIRROR','EVENT','BOSSPQ','HAPPYVILLE','MONSTER_CARNIVAL','MONSTER_PARK','DEVELOPER') NOT NULL;
